# -*- coding: utf-8 -*-
"""facial_expression_model_inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qJHresE-FfJ6Q8DH7bGw6Iiji4b3--RR
"""

# from google.colab import drive
# drive.mount('/content/drive')

"""##**Libraries**"""

# Import needed packages
import os
import numpy as np
import cv2
# from keras.models import Sequential
# from keras.layers import Dense
from keras.models import load_model

# from google.colab.patches import cv2_imshow

"""##**Generate predictions**"""

def activity_model_inference(image_frame):
    #work in progress

    ret, jpeg = cv2.imencode('.jpg', image_frame)
    return jpeg.tobytes(), jpeg

